services:
  builder:
    build:
      context: ./containers/ubuntu-jammy-21
      dockerfile: Dockerfile
    container_name: replacement_builder
    hostname: replacement_build
    volumes:
      - .:/firmware
    user: build
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb/"